name: badua

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'temurin'
      - name: Clone and build ba-dua  # to get the CLI
        run: |
          git clone https://www.github.com/saeg/ba-dua.git
          cd ba-dua
          git checkout tags/ba-dua-0.8.0 -b ba-dua-0.8.0
          mvn clean install
      - name: Build
        run: mvn clean verify -P badua
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: badua-report
          path: zookeeper-server/target/badua.xml
          if-no-files-found: error